SSAFY_1학기/django/django-master-01_django_model/01_django_model/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
]

SSAFY_1학기/django/django-master-01_django_model/01_django_model/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

SSAFY_1학기/django/django-master-01_django_model/01_django_model/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

SSAFY_1학기/django/django-master-01_django_model/01_django_model/articles/views.py
from django.shortcuts import render, redirect #, redirect 둘중에 하나만 
from .models import Article #명시적 상대 경로
# Create your views here.
def index(request):
    #작성한 모든 게시글을 출력
    # 1. 모든 게시글 조회
    articles = Article.objects.order_by('-pk')
    context = {
        'articles' : articles,
    }
    return render(request, 'articles/index.html', context)

def new(request):
    return render(request, 'articles/new.html')


def create(request):
    #new 로부터 title과 content 를 받아서 저장
    title = request.POST.get('title')
    content = request.POST.get('content')
    # 1번째 방법
    # article = Article()
    # article.title = title
    # article.content = content
    # article.save()
    # 2 번째 방법  앞으로 이방법 쓸거임 저장전에 유효성 검사를 위해서임
    article = Article(title=title, content = content)
    article.save()
    # 3번째 방법
    # Article.objects.create(title = title, content=content)
    return redirect('articles:detail', article.pk)
def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context ={
        'article' : article,
    }
    return render(request, 'articles/detail.html', context)

def delete(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == 'POST':
        article.delete()
        return redirect('articles:index')
    else:
        return redirect('articles:detail', article.pk)

def edit(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article' : article,
    }
    return render(request, 'articles/edit.html', context)

def update(request, pk):
    article =Article.objects.get(pk=pk)
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()
    return redirect('articles:detail', article.pk)

SSAFY_1학기/django/django-master-01_django_model/01_django_model/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
  <h1 class='text-center'>성공적으로 글이 작성되었습니다</h1>
{% endblock %}

SSAFY_1학기/django/django-master-01_django_model/01_django_model/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
  <h2 class='text-center'>DETAIL</h2>
  <h3> {{ article.pk }}번째 글 </h3>
  <hr>
  <p>제목 : {{article.title}}</p>
  <p>내용 : {{ article.content }}</p>
  <p>작성시각 : {{article.created_at}}</p>
  <p>수정시각 : {{article.updated_at}}</p>
  <hr>
  <a href="{% url 'articles:edit' article.pk %}" class="btn btn-primary">EDIT</a><br>
  <form action="{% url 'articles:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <button class="btn">DELETE</button>
  </form>
  <a href="{% url 'articles:index' %}">back</a>
{% endblock %}

SSAFY_1학기/django/django-master-01_django_model/01_django_model/articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block content %}
  <h1 class='text-center'>EDIT</h1>
  <form action="{% url 'articles:update' article.pk %}" method="POST">
    {% csrf_token %}
    <label for="title">Title: </label>
    <input type="text" name="title" value="{{ article.title }}"<br>
    <label for="content">Content: </label>
    <textarea name="content" cols="30" rows="5"> {{ article.content }}</textarea><br>
    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'articles:index' %}"> back</a>
{% endblock %}

SSAFY_1학기/django/django-master-01_django_model/01_django_model/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center">Articles</h1>
  <a href={% url 'articles:new' %}>NEW</a>
  {% for article in articles %}
    <p>글 번호 : {{ article.pk }} </p>
    <p>제목 : {{ article.title }}</p>
    <p>내용 : {{ article.content }}</p>
    <a href={% url 'articles:detail' article.pk %}> detail</a>
    <hr>
  {% endfor %}
{% endblock %}

SSAFY_1학기/django/django-master-01_django_model/01_django_model/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
  <h1 class='text-center'>NEW</h1>
  <form action="{% url 'articles:create' %}" method='POST'>
    {% csrf_token %}
    <label for="title">Title:</label>
    <input type="text", id="title" name="title">
    <label for="content">Content:</label>
    <textarea name="content" id="content" cols="30" rows="10"></textarea>
    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'articles:index' %}"> back </a>
{% endblock %}

SSAFY_1학기/django/django-master-01_django_model/01_django_model/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
  <title>Document</title>
</head>
<body>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
</body>
</html>